"""Create Table Categorias de Produtos

Revision ID: 0bc01393f025
Revises: 
Create Date: 2024-08-28 13:49:30.758996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc01393f025'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('codigo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    # ### end Alembic commands ###
